### ISSUE TITLE
There is a huge difference in the search results of pg_cjk_parser and zhparser

### ISSUE THREAD

**Issue by aaro-n** [huangjimmy/pg_cjk_parser#10]
# introduce
I'm not a computer professional, I just want the Miniflux I built to be able to search for more content.
# Deployment method
Both pg_cjk_parse and zhparser build images and run them through docker-compose.yml.
# Test search content
When Miniflux uses pg_cjk_parse and zhparser as databases respectively, the same RSS entries are imported and forced to refresh. After waiting for a period of time, pg_cjk_parse gets 7829 unread items and zhparser gets 7824 unread items.
I tested Chinese and English in the search respectively, and found that the number given by pg_cjk_parse was much smaller than that of zhparser. For example, searching for `Hangzhou`, pg_cjk_parse showed 28 entries, and zhparser showed 123 entries. When searching for English, pg_cjk_parse and zhparser would also have differences. , in general, pg_cjk_parse will search for fewer entries.
# question
1. I have installed several extensions on zhparser, will these have any impact?
2. Is pg_cjk_parse enabled correctly?
# Schedule
## pg_cjk_parse
docker-compose.yml
```
version: '3'
services:
   postgres:
     build:
       context: /home/www/miniflux/pg_cjk_parser
       dockerfile: Dockerfile
     image: pg_cjk_parser
     container_name: postgres
     environment:
       - POSTGRES_PASSWORD=vg9QUVgeyjsQq6jwi5PsHZSDKWFReFZzKzNaPZ8X
     volumes:
       - /home/www/miniflux/pg_cjk_parser/database:/var/lib/postgresql/data
     networks:
       - pg_cjk_parser

   pgAdmin:
     restart: always
     image: dpage/pgadmin4
     ports:
       - "8085:80"
     environment:
       PGADMIN_DEFAULT_EMAIL: xx@gmail.com
       PGADMIN_DEFAULT_PASSWORD: 123
     networks:
       - pg_cjk_parser

   miniflux:
     restart: always
     image: miniflux/miniflux:latest
     ports:
       - "8086:8080"
     environment:
       - DATABASE_URL=postgres://postgres:vg9QUVgeyjsQq6jwi5PsHZSDKWFReFZzKzNaPZ8X@postgres:5432/postgres?sslmode=disable
       - RUN_MIGRATIONS=1
       - CREATE_ADMIN=1
       - ADMIN_USERNAME=admin
       -ADMIN_PASSWORD=test123
     networks:
       - pg_cjk_parser

networks:
   pg_cjk_parser:
     driver:bridge
```
Dockerfile
```
ARG POSTGRES_VERSION=16
FROM postgres:$POSTGRES_VERSION as build
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates git postgresql-server-dev-16 gcc make icu-devtools libicu-dev

RUN mkdir -p /root/parser
WORKDIR /root/parser
RUN git clone https://github.com/huangjimmy/pg_cjk_parser.git /tmp/pg_cjk_parser && \
     cp /tmp/pg_cjk_parser/pg_cjk_parser.c /tmp/pg_cjk_parser/pg_cjk_parser.control /tmp/pg_cjk_parser/Makefile /tmp/pg_cjk_parser/pg_cjk_parser--0.0.1.sql /tmp/pg_cjk_parser/zht2zh s.h /root/parser/ && \
     make clean && make install

FROM postgres:$POSTGRES_VERSION
ARG POSTGRES_VERSION=16
COPY --from=build /root/parser/pg_cjk_parser.bc /usr/lib/postgresql/$POSTGRES_VERSION/lib/bitcode
COPY --from=build /root/parser/pg_cjk_parser.so /usr/lib/postgresql/$POSTGRES_VERSION/lib
COPY --from=build /root/parser/pg_cjk_parser--0.0.1.sql /usr/share/postgresql/$POSTGRES_VERSION/extension
COPY --from=build /root/parser/pg_cjk_parser.control /usr/share/postgresql/$POSTGRES_VERSION/extension
```

1. Build the image and run it, log in with pgAdmin, and configure the connection database
2. Select `CREATE script` on the `postgres` database, and a new window will pop up.
3. Clear the window content and enter
```
CREATE TEXT SEARCH PARSER public.pg_cjk_parser (
     START = prsd2_cjk_start,
     GETTOKEN = prsd2_cjk_nexttoken,
     END = prsd2_cjk_end,
     LEXTYPES = prsd2_cjk_lextype,
     HEADLINE = prsd2_cjk_headline);

CREATE TEXT SEARCH CONFIGURATION public.config_2_gram_cjk (
     PARSER = pg_cjk_parser
);

SET default_text_search_config = 'public.config_2_gram_cjk';
```
Click Run and clear the input
```
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR asciihword
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR cjk
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR email
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR asciiword
     WITH english_stem;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR entity
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR file
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR float
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR host
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR hword
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR hword_asciipart
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR hword_numpart
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR hword_part
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR int
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR numhword
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR numword
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR protocol
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR sfloat
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR tag
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
     ADD MAPPING FOR uint
     WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
    ADD MAPPING FOR url
    WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
    ADD MAPPING FOR url_path
    WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
    ADD MAPPING FOR version
    WITH simple;

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk
    ADD MAPPING FOR word
    WITH simple;
```
4. Log in to Miniflux through the normal installation process and import RSS feeds.
## zhparser
docker-compose.yml
```
version: '3'
services:
  postgres:
    build:
      context: /home/www/miniflux/zhparser
      dockerfile: Dockerfile
    image: zhparser
    container_name: zhparser
    environment:
      - POSTGRES_PASSWORD=vg9QUVgeyjsQq6jwi5PsHZSDKWFReFZzKzNaPZ8X
    volumes:
      - /home/www/miniflux/zhparser/database:/var/lib/postgresql/data
    networks:
      - zhparser

  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - "8095:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: xxx@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    networks:
      - zhparser

  miniflux:
    restart: always
    image: miniflux/miniflux:latest 
    ports:
      - "8096:8080"
    environment:
      - DATABASE_URL=postgres://postgres:vg9QUVgeyjsQq6jwi5PsHZSDKWFReFZzKzNaPZ8X@zhparser:5432/postgres?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
    networks:
      - zhparser

networks:
  zhparser:
    driver: bridge
```
Dockerfile
```
FROM postgres:16-bullseye

LABEL maintainer="loyayz - https://loyayz.com"

ENV SCWS_URL http://www.xunsearch.com/scws/down/scws-1.2.3.tar.bz2
ENV ZHPARSER_URL https://github.com/amutu/zhparser/archive/refs/heads/master.tar.gz
ENV SAFEUPDATE_URL https://github.com/eradman/pg-safeupdate/archive/master.tar.gz
ENV PG_CRON_URL https://github.com/citusdata/pg_cron/archive/main.tar.gz

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
           ca-certificates \
           wget \
           bzip2 \
           make \
           gcc \
           libc6-dev \
           postgresql-16-cron \
           postgresql-server-dev-$PG_MAJOR \
           \
      ## install scws
      && cd / \
      && wget -q -O - $SCWS_URL | tar xjf - \
      && SCWS_DIR=${SCWS_URL##*/} \
      && SCWS_DIR=${SCWS_DIR%%.tar*} \
      && cd $SCWS_DIR && ./configure && make install \
      ## install zhparser
      && cd / \
      && wget -q -O - $ZHPARSER_URL | tar xzf - \
      && cd zhparser-master && make install \
      ## install pg-safeupdate
      && cd / \
      && wget -q -O - $SAFEUPDATE_URL | tar xzf - \
      && cd pg-safeupdate-master && gmake && make install \
      # clean
      && apt-get purge -y \
            bzip2 \
            make \
            gcc \
            libc6-dev \
            postgresql-server-dev-$PG_MAJOR \
      && apt-get autoremove --purge -y \
      && rm -rf /$SCWS_DIR \
            /zhparser-master \
            /pg-safeupdate-master \
            /var/lib/apt/lists/*

RUN mkdir -p /docker-entrypoint-initdb.d \
    && wget https://raw.githubusercontent.com/aaro-n/miniflux-postgres/main/config/init_extension.sh -O /docker-entrypoint-initdb.d/init_extension.sh
RUN chmod 755 /docker-entrypoint-initdb.d/init_extension.sh
```
1. Build the image and run it, log in with pgAdmin, and configure the connection database
2. Select `CREATE script` on the `postgres` database, and a new window will pop up.
3. Clear the window content and enter
```
CREATE TEXT SEARCH CONFIGURATION chinese (PARSER = zhparser);
```
Run, then clear, enter
```
ALTER TEXT SEARCH CONFIGURATION chinese ADD MAPPING FOR n,v,a,i,e,l WITH simple;
```
Run again, clear, enter
```
CREATE EXTENSION pg_stat_statements;
```
run
4. Log in to Miniflux through the normal installation process and import RSS feeds.

**Comment by aaro-n** [comment]
又简单测试了下，当RSS源语言是中文时，pg_cjk_parser和zhparser搜索出来的数量各有胜负，当RSS源主要语言是日文时pg_cjk_parser搜索出的数量远超zhparser，韩文未作测试。
# 方法
## Docker配置
 docker-compose.yml 
```
www@CN2:~/komodo/pg_cjk$ cat docker-compose.yml 
services:
  miniflux:
    image: miniflux/miniflux:latest
    restart: always
    ports:
      - "28080:8080"
    depends_on:
      cjk:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux88888888@cjk/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
  cjk:
    build:
       context: /home/www/komodo/pg_cjk
       dockerfile: Dockerfile
    restart: always
    container_name: cjk
    ports:
      - "35676:5432"
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=88888888
      - POSTGRES_DB=miniflux
    volumes:
      - cjk-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
volumes:
  cjk-db:
```
Dockerfile 
```
www@CN2:~/komodo/pg_cjk$ cat Dockerfile 
ARG POSTGRES_VERSION=16
FROM postgres:$POSTGRES_VERSION as build
ARG POSTGRES_VERSION=16
RUN apt-get update && apt-get install -y --no-install-recommends postgresql-server-dev-$POSTGRES_VERSION gcc make icu-devtools libicu-dev ca-certificates git

RUN mkdir -p /root/parser
WORKDIR /root/parser
RUN git clone https://github.com/huangjimmy/pg_cjk_parser.git /tmp/pg_cjk_parser && \     
    cp /tmp/pg_cjk_parser/pg_cjk_parser.c /root/parser/ && \
    cp /tmp/pg_cjk_parser/pg_cjk_parser.control /root/parser/ && \
    cp /tmp/pg_cjk_parser/Makefile /root/parser/ && \
    cp /tmp/pg_cjk_parser/pg_cjk_parser--0.0.1.sql /root/parser/ && \
    cp /tmp/pg_cjk_parser/zht2zhs.h /root/parser/ && \
    make clean && make install

FROM postgres:$POSTGRES_VERSION
ARG POSTGRES_VERSION=16
COPY --from=build /root/parser/pg_cjk_parser.bc /usr/lib/postgresql/$POSTGRES_VERSION/lib/bitcode
COPY --from=build /root/parser/pg_cjk_parser.so /usr/lib/postgresql/$POSTGRES_VERSION/lib
COPY --from=build /root/parser/pg_cjk_parser--0.0.1.sql /usr/share/postgresql/$POSTGRES_VERSION/extension
COPY --from=build /root/parser/pg_cjk_parser.control /usr/share/postgresql/$POSTGRES_VERSION/extension
```
## 数据库配置
1. 登录数据库并进行基础配置，要先配置数据库，再运行miniflux
```
登录数据库

PGPASSWORD='88888888' psql -U miniflux -d miniflux

启用插件

CREATE EXTENSION pg_cjk_parser;

创建解析器和配置 

CREATE TEXT SEARCH PARSER public.pg_cjk_parser (
    START = prsd2_cjk_start,
    GETTOKEN = prsd2_cjk_nexttoken,
    END = prsd2_cjk_end,
    LEXTYPES = prsd2_cjk_lextype,
    HEADLINE = prsd2_cjk_headline);

CREATE TEXT SEARCH CONFIGURATION public.config_2_gram_cjk (
    PARSER = pg_cjk_parser
);

SET default_text_search_config = 'public.config_2_gram_cjk';

或

CREATE TEXT SEARCH PARSER public.pg_cjk_parser (START = prsd2_cjk_start, GETTOKEN = prsd2_cjk_nexttoken, END = prsd2_cjk_end, LEXTYPES = prsd2_cjk_lextype, HEADLINE = prsd2_cjk_headline); CREATE TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ( PARSER = pg_cjk_parser ); SET default_text_search_config = 'public.config_2_gram_cjk';

添加所有必要的词典映射  

ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR asciihword WITH simple;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR cjk WITH simple;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR email WITH simple;  
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR asciiword WITH english_stem;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR entity WITH simple;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR file WITH simple;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR float WITH simple; 
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR host WITH simple;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR hword WITH simple;  
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR hword_asciipart WITH simple;  
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR hword_numpart WITH simple;  
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR hword_part WITH simple;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR int WITH simple;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR numhword WITH simple;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR numword WITH simple;  
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR protocol WITH simple;  
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR sfloat WITH simple;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR tag WITH simple;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR uint WITH simple;
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR url WITH simple; 
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR url_path WITH simple; 
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR version WITH simple;  
ALTER TEXT SEARCH CONFIGURATION public.config_2_gram_cjk ADD MAPPING FOR word WITH simple;

配置默认解析器

miniflux=# SELECT * FROM pg_ts_config;
  oid  |      cfgname      | cfgnamespace | cfgowner | cfgparser 
-------+-------------------+--------------+----------+-----------
  3748 | simple            |           11 |       10 |      3722
 13157 | arabic            |           11 |       10 |      3722
 13159 | armenian          |           11 |       10 |      3722
 13161 | basque            |           11 |       10 |      3722
 13163 | catalan           |           11 |       10 |      3722
 13165 | danish            |           11 |       10 |      3722
 13167 | dutch             |           11 |       10 |      3722
 13169 | english           |           11 |       10 |      3722
 13171 | finnish           |           11 |       10 |      3722
 13173 | french            |           11 |       10 |      3722
 13175 | german            |           11 |       10 |      3722
 13177 | greek             |           11 |       10 |      3722
 13179 | hindi             |           11 |       10 |      3722
 13181 | hungarian         |           11 |       10 |      3722
 13183 | indonesian        |           11 |       10 |      3722
 13185 | irish             |           11 |       10 |      3722
 13187 | italian           |           11 |       10 |      3722
 13189 | lithuanian        |           11 |       10 |      3722
 13191 | nepali            |           11 |       10 |      3722
 13193 | norwegian         |           11 |       10 |      3722
 13195 | portuguese        |           11 |       10 |      3722
 13197 | romanian          |           11 |       10 |      3722
 13199 | russian           |           11 |       10 |      3722
 13201 | serbian           |           11 |       10 |      3722
 13203 | spanish           |           11 |       10 |      3722
 13205 | swedish           |           11 |       10 |      3722
 13207 | tamil             |           11 |       10 |      3722
 13209 | turkish           |           11 |       10 |      3722
 13211 | yiddish           |           11 |       10 |      3722
 16397 | config_2_gram_cjk |         2200 |       10 |     16396
(30 rows)

检查解析器是否正确创建

miniflux=# SELECT * FROM pg_ts_parser WHERE oid = 16396;
  oid  |    prsname    | prsnamespace |    prsstart     |      prstoken       |    prsend     |    prsheadline     |    prslextype     
-------+---------------+--------------+-----------------+---------------------+---------------+--------------------+-------------------
 16396 | pg_cjk_parser |         2200 | prsd2_cjk_start | prsd2_cjk_nexttoken | prsd2_cjk_end | prsd2_cjk_headline | prsd2_cjk_lextype
(1 row)

检查词典映射是否完整

miniflux=# SELECT * FROM pg_ts_config_map WHERE mapcfg = 16397;
 mapcfg | maptokentype | mapseqno | mapdict 
--------+--------------+----------+---------
  16397 |            1 |        1 |   13168
  16397 |            2 |        1 |    3765
  16397 |            3 |        1 |    3765
  16397 |            4 |        1 |    3765
  16397 |            5 |        1 |    3765
  16397 |            6 |        1 |    3765
  16397 |            7 |        1 |    3765
  16397 |            8 |        1 |    3765
  16397 |            9 |        1 |    3765
  16397 |           10 |        1 |    3765
  16397 |           11 |        1 |    3765
  16397 |           13 |        1 |    3765
  16397 |           14 |        1 |    3765
  16397 |           15 |        1 |    3765
  16397 |           16 |        1 |    3765
  16397 |           17 |        1 |    3765
  16397 |           18 |        1 |    3765
  16397 |           19 |        1 |    3765
  16397 |           20 |        1 |    3765
  16397 |           21 |        1 |    3765
  16397 |           22 |        1 |    3765
  16397 |           23 |        1 |    3765
  16397 |           24 |        1 |    3765
(23 rows)

验证当前默认配置


miniflux=# SHOW default_text_search_config;
 default_text_search_config 
----------------------------
 public.config_2_gram_cjk
(1 row)

要注意，如何输出的不是public.config_2_gram_cjk，可以执行 ALTER DATABASE miniflux SET default_text_search_config = 'public.config_2_gram_cjk';  后退出pgsql，再进入，验证SHOW default_text_search_config; 或修改postgresql.conf，添加default_text_search_config = 'public.config_2_gram_cjk'  

之后就可以正常使用了。
```

在https://deepwiki.com/ 帮助下，进行验证
